{
    'name': 'Hospital Management',
    'version': '1.0',
    'summary': 'Hospital Management Software',
    'sequence': 10,
    'description': """ Hospital Management Software""",
    'category': 'Productivity',
    'website': 'https://www.odoo.com/',
    'depends': ['base', 'sale', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'wizard/create_appointment_view.xml',
        'wizard/search_appointment.xml',
        'views/patient_view.xml',
        'views/template.xml',
        'views/template_2.xml',
        'views/sale.xml',
        'views/kids_view.xml',
        'views/appointment_view.xml',
        'views/patient_gender_view.xml',
        'views/product_views.xml',
        'views/customer_views.xml',
        'views/abstract_menu.xml',
        'views/doctor_view.xml'
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto install': False,
    'license': 'LGPL-3',
}
